### ISSUE TITLE
Varta QA

### ISSUE THREAD

**Issue by vv-monsalve** [SorkinType/Varta#4]
Given the mentioned status of the project:

> No FontBakery Tests have been done on this by me. It may make sense to re-build the OT features for this because Glyphs will probably do a much better job with it now. This originally had features but Dave indicated at one point that they disappeared! I can talk to the other designers to look for copies that have the old features intact in them. It is also likely that some manually written OT features were made for this as well to reflect the discretionary nature of Devanagari conjuncts. Getting this to 100% is likely to be the most complex for reasons of software changes and script.

The following was done in order to assess the real status of it:

Open the Varta-MultipleMaster.glyphs to see what most recent version of app warns. 

### At open:

![Glyphs alert at open](https://user-images.githubusercontent.com/48698976/62958318-111b1680-bdbc-11e9-8473-a5c031df25f8.png)

### **Checking GF Latin Core**
List of missing glyphs:

![Varta-LatinCore-missing-glyphs](https://user-images.githubusercontent.com/48698976/62959831-01510180-bdbf-11e9-8f18-4c39b26bb22d.png)

### **Checking Features** 
After that features panel was open and tried to automatically update some features list. There were some message errors; looked up for one, "matra-deva", and find [this](https://forum.glyphsapp.com/t/devnagari-opentype-error/9355). Tried its suggestions but still got the errors.

**Devanagari missing glyphs**

![Varta-deva-missing-glyphs1](https://user-images.githubusercontent.com/48698976/62960256-ea5edf00-bdbf-11e9-89dc-c3917c809c6e.png)
![Varta-deva-missing-glyphs2](https://user-images.githubusercontent.com/48698976/62960258-ea5edf00-bdbf-11e9-91c3-e929f8aa4550.png)

**Couple of pictures of messages as error examples.**

![Fea-Aalt-orig](https://user-images.githubusercontent.com/48698976/62960173-baafd700-bdbf-11e9-857a-33694e533895.png)
![Fea-Aalt-message](https://user-images.githubusercontent.com/48698976/62960190-c13e4e80-bdbf-11e9-8bfc-e91f061bfad4.png)

![Fea-ccmp-orig](https://user-images.githubusercontent.com/48698976/62960360-1d08d780-bdc0-11e9-892a-d3b1083be8ad.png)
![Fea-ccmp-message](https://user-images.githubusercontent.com/48698976/62960369-209c5e80-bdc0-11e9-99d7-939fdc6e3d8e.png)

**Comment by EbenSorkin** [comment]
Much of this is solved for now with a revised source. The Micro I added myself and created the other parallel symbol/Greek glyphs as well ( Omega /Ohm for example)
